name: deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Chectout
      uses: actions/checkout@v4
    -
      name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: $[{ secrets.DOKERHUB_USERNAME }]
        password: $[{ secrets.DOKERHUB_TOKEN }]
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push
      uses: docker/build-push/action@v5
      with: 
        contex: .
        file: ./Dockerfile
        push: true
        tags: $[{ secrets.DOCKERHUB_USERNAME }]/nest-demo:latests
    
